config/routes.rb
Telinfo::Application.routes.draw do
  resources :histories

end

app/models/history.rb
class History < ActiveRecord::Base
  attr_accessible :acceptance_at, :acceptance_user, :category, :completion_on, :customer_name, :customer_no, :customer_user, :details, :first_contact_at, :incident_no, :necessity_contact, :period_contact_on, :primary_user, :priority, :rank, :status, :support_user, :target, :target_on, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @histories }
    end
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
    @history = History.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @history }
    end
  end

  # GET /histories/new
  # GET /histories/new.json
  def new
    @history = History.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @history }
    end
  end

  # GET /histories/1/edit
  def edit
    @history = History.find(params[:id])
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(params[:history])

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render json: @history, status: :created, location: @history }
      else
        format.html { render action: "new" }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /histories/1
  # PUT /histories/1.json
  def update
    @history = History.find(params[:id])

    respond_to do |format|
      if @history.update_attributes(params[:history])
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history = History.find(params[:id])
    @history.destroy

    respond_to do |format|
      format.html { redirect_to histories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.haml
= simple_form_for @history, :html => { :class => 'form-horizontal' } do |f|
  = f.input :incident_no
  = f.input :customer_no
  = f.input :customer_name
  = f.input :rank
  = f.input :status
  = f.input :acceptance_user
  = f.input :customer_user
  = f.input :primary_user
  = f.input :support_user
  = f.input :title
  = f.input :details
  = f.input :category
  = f.input :target
  = f.input :priority
  = f.input :necessity_contact
  = f.input :period_contact_on
  = f.input :acceptance_at
  = f.input :first_contact_at
  = f.input :target_on
  = f.input :completion_on
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), histories_path, :class => 'btn'

app/views/histories/edit.html.haml
- model_class = History
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/histories/index.html.haml
- model_class = History
.page-header
  %h1=t '.title', :default => model_class.model_name.human
%table.table.table-striped.table-bordered.table-condensed
  %thead
    %tr
      %th= model_class.human_attribute_name(:incident_no)
      %th= model_class.human_attribute_name(:customer_no)
      %th(colspan=2)= model_class.human_attribute_name(:customer_name)
      %th= model_class.human_attribute_name(:rank)
      %th(rowspan=2)= model_class.human_attribute_name(:title)
      %th(rowspan=2)= model_class.human_attribute_name(:details)
      %th= model_class.human_attribute_name(:category)
      %th= model_class.human_attribute_name(:priority)
      %th= model_class.human_attribute_name(:period_contact_on)
      %th(rowspan=2)= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:target_on)
      %th(colspan=2 rowspan=2)=t '.actions', :default => t("helpers.actions")
    %tr
      %th= model_class.human_attribute_name(:acceptance_at)
      %th= model_class.human_attribute_name(:acceptance_user)
      %th= model_class.human_attribute_name(:customer_user)
      %th= model_class.human_attribute_name(:primary_user)
      %th= model_class.human_attribute_name(:support_user)
      %th= model_class.human_attribute_name(:target)
      %th= model_class.human_attribute_name(:necessity_contact)
      %th= model_class.human_attribute_name(:first_contact_at)
      %th= model_class.human_attribute_name(:completion_on)
  %tbody
    - @histories.each do |history|
      %tr
        %td= history.incident_no
        %td= history.customer_no
        %td(colspan=2)= history.customer_name
        %td= history.rank
        %td(rowspan=2)= history.title
        %td(rowspan=2)= history.details
        %td= history.category
        %td= history.priority
        %td= l history.period_contact_on, :format => :short
        %td(rowspan=2)= history.status
        %td= l history.target_on, :format => :short
        %td(colspan=2 rowspan=2)
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_history_path(history), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), history_path(history), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
      %tr
        %td= l history.acceptance_at, :format => :short
        %td= history.acceptance_user
        %td= history.customer_user
        %td= history.primary_user
        %td= history.support_user
        %td= history.target
        %td= history.necessity_contact
        %td= l history.first_contact_at, :format => :short
        %td= l history.completion_on, :format => :short

= link_to t('.new', :default => t("helpers.links.new")), new_history_path, :class => 'btn btn-primary'

app/views/histories/new.html.haml
- model_class = History
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/histories/show.html.haml
- model_class = History
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:incident_no) + ':'
  %br
  = @history.incident_no
%p
  %strong= model_class.human_attribute_name(:customer_no) + ':'
  %br
  = @history.customer_no
%p
  %strong= model_class.human_attribute_name(:customer_name) + ':'
  %br
  = @history.customer_name
%p
  %strong= model_class.human_attribute_name(:rank) + ':'
  %br
  = @history.rank
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @history.status
%p
  %strong= model_class.human_attribute_name(:acceptance_user) + ':'
  %br
  = @history.acceptance_user
%p
  %strong= model_class.human_attribute_name(:customer_user) + ':'
  %br
  = @history.customer_user
%p
  %strong= model_class.human_attribute_name(:primary_user) + ':'
  %br
  = @history.primary_user
%p
  %strong= model_class.human_attribute_name(:support_user) + ':'
  %br
  = @history.support_user
%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @history.title
%p
  %strong= model_class.human_attribute_name(:details) + ':'
  %br
  = @history.details
%p
  %strong= model_class.human_attribute_name(:category) + ':'
  %br
  = @history.category
%p
  %strong= model_class.human_attribute_name(:target) + ':'
  %br
  = @history.target
%p
  %strong= model_class.human_attribute_name(:priority) + ':'
  %br
  = @history.priority
%p
  %strong= model_class.human_attribute_name(:necessity_contact) + ':'
  %br
  = @history.necessity_contact
%p
  %strong= model_class.human_attribute_name(:period_contact_on) + ':'
  %br
  = @history.period_contact_on
%p
  %strong= model_class.human_attribute_name(:acceptance_at) + ':'
  %br
  = @history.acceptance_at
%p
  %strong= model_class.human_attribute_name(:first_contact_at) + ':'
  %br
  = @history.first_contact_at
%p
  %strong= model_class.human_attribute_name(:target_on) + ':'
  %br
  = @history.target_on
%p
  %strong= model_class.human_attribute_name(:completion_on) + ':'
  %br
  = @history.completion_on

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), histories_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_history_path(@history), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), history_path(@history), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Telinfo"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Telinfo
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        .span12
          = yield
    
      %footer
        %p &copy; k.fujii 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"